<div class="jumbotron mt-5">
    <h1>Welcome to <span class="zf-green">Dzen Code Guestbook!</span></h1>
    <p>
        Great! We successfully completed the task.
        Now you can validate it.
    </p>
    <p><a class="btn btn-success btn-lg" href="https://github.com/sumtsow/dzen" target="_blank">Fork Dzen Code Guestbook on GitHub &raquo;</a></p>
</div>
<div class="row">
    <div class="col">
    <?php outRecusively($comments); ?>
    </div>
</div>
<p>
    <a class="btn btn-success my-3" href="<?php /*echo $this->url('comment', ['action' => 'add'])*/ ?>">Add new comment &raquo;</a>
</p>

<?php
    function outRecusively($comments) {
    foreach($comments as $comment) :
?>
        <div class="panel panel-default mx-3">
            <div class="panel-heading">
                <h3 class="panel-title"><span class="font-weight-bold"><?= $comment->user_name; ?></span> <?= (strftime("%d.%m.%Y в %H:%m ", strtotime($comment->created_at))); ?></h3>
            </div>
            <div class="panel-body">
                <p><?= $comment->text; ?></p>
                <p><a class="btn btn-success float-right" href="<?php /*echo $this->url('comment', ['action' => 'add'])*/ ?>">Answer &raquo;</a></p>
            </div>
<?php
        if ($comment->children) :
            outRecusively($comment->children);
?>
        </div>
    </div>
<?php
        endif;
    endforeach; 
}
