<?php
if ($this->pageCount):
?>
<ul class="pagination mt-3 mb-0">
<!-- Previous page link -->
<?php if (isset($this->previous)): ?>
<li class="page-item">
  <a class="page-link" href="<?= $this->url($this->route, array(
      'action'=>'index',
      'page' => $this->previous,
  )); ?>">&larr;Prev</a>
</li>
<?php endif; ?>

<!-- Numbered page links -->
<?php foreach ($this->pagesInRange as $page):
    ($page == $this->current) ? $active = ' active' : $active = '' ?>
<li class="page-item<?= $active; ?>">
    <a class="page-link" href="<?= $this->url($this->route, [
        'action'=>'index',
        'page' => $page,
    ]); ?>"><?= $page; ?></a>
</li>    
<?php endforeach; ?>
    
<!-- Next page link -->
<?php if (isset($this->next)): ?>
<li class="page-item">
  <a class="page-link" href="<?= $this->url($this->route, array(
      'action'=>'index',
      'page' => $this->next,
  )); ?>">Next&rarr;</a>
</li>
<?php endif; ?>
</ul>
<?php endif; ?>
